version: '3.1'
services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:4.2.8
    restart: always
    command: --bind_ip_all --dbpath "/data/db" --replSet "rs0"
    expose:
      - 27017
    ports: 
      - 27017:27017
    volumes:
      - ~/mongo/realtimedashboard/db:/data/db